### ISSUE TITLE
Fatal Error when encountering Gii templates in extensions.

### ISSUE THREAD

**Issue by daxpresents** [laMarciana/yiiDocumentor#1]
Building model...
PHP Fatal error:  Using $this when not in object context

This is happening with the bootstrap extension and the gtc extension, it works fine if you remove the Gii templates but it would be really great to not have to do that.

**Comment by laMarciana** [comment]
The problem is that all files are needed to be included (and then are executed), so unexpected problems can arise. A mechanism to include files but getting just its classes defined without running anything more would be needed. At the moment I can't think any efficient way (getting file contents of each file and do regex it's too heavy) so I have added an `exclude` configuration option as a workaround. In it, any directory or file giving problems can be added and then it won't be included. Look at the documentation for details.
